name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Fetch all tags
      run: git fetch --tags
      
    - name: Get latest tag
      id: latest-tag
      run: |
          TAG=$(git tag --sort=v:refname | tail -n 1)
          echo "Latest tag is $TAG"
          echo "::set-output name=tag::${TAG}"
          
    - name: Increment version
      id: increment-version
      run: |
          TAG="${{ steps.latest-tag.outputs.tag }}"
          BASE_VERSION=${TAG#v} # Strip the 'v' prefix
          IFS='.' read -ra VERSION <<< "$BASE_VERSION"
          PATCH=$((VERSION[2]+1))
          NEXT_VERSION="v${VERSION[0]}.${VERSION[1]}.$PATCH"
          echo "Next version is $NEXT_VERSION"
          echo "::set-output name=version::$NEXT_VERSION"

    - name: Create new tag
      run: |
          git tag ${{ steps.increment-version.outputs.version }}
          git push origin ${{ steps.increment-version.outputs.version }}

    - name: Install Java and Maven
      run: |
          set -e  
          sudo apt update
          sudo apt install -y wget unzip tar

          JDK_VERSION=21.0.4+7
          JDK_DOWNLOAD_URL="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.4_7.tar.gz"
          wget $JDK_DOWNLOAD_URL -O openjdk-21.tar.gz
          sudo mkdir -p /opt/java
          sudo tar -xzf openjdk-21.tar.gz -C /opt/java
          
          sudo ln -sf /opt/java/jdk-21.0.4+7/bin/java /usr/bin/java
          sudo ln -sf /opt/java/jdk-21.0.4+7/bin/javac /usr/bin/javac
          
          export JAVA_HOME=/opt/java/jdk-21.0.4+7
          export PATH=$JAVA_HOME/bin:$PATH
          
          echo "Java version:"
          java -version
          echo "Javac version:"
          javac -version
          
          MAVEN_VERSION=3.9.10
          MAVEN_DOWNLOAD_URL="https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz"
          wget $MAVEN_DOWNLOAD_URL -O apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo tar -xvf apache-maven-$MAVEN_VERSION-bin.tar.gz -C /opt/
          sudo ln -sf /opt/apache-maven-$MAVEN_VERSION/bin/mvn /usr/bin/mvn
          
          export M2_HOME=/opt/apache-maven-$MAVEN_VERSION
          export PATH=$M2_HOME/bin:$PATH
          
          echo "Maven version:"
          mvn -version
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.REPO_NAME }}/mvn:${{ steps.increment-version.outputs.version }}
          ${{ secrets.REPO_NAME }}/mvn:latest
