name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Fetch all tags
      run: git fetch --tags
      
    - name: Get latest tag
      id: latest-tag
      run: |
          TAG=$(git tag --sort=v:refname | tail -n 1)
          echo "Latest tag is $TAG"
          echo "::set-output name=tag::${TAG}"
          
    - name: Increment version
      id: increment-version
      run: |
          TAG="${{ steps.latest-tag.outputs.tag }}"
          BASE_VERSION=${TAG#v} # Strip the 'v' prefix
          IFS='.' read -ra VERSION <<< "$BASE_VERSION"
          PATCH=$((VERSION[2]+1))
          NEXT_VERSION="v${VERSION[0]}.${VERSION[1]}.$PATCH"
          echo "Next version is $NEXT_VERSION"
          echo "::set-output name=version::$NEXT_VERSION"

    - name: Create new tag
      run: |
          git tag ${{ steps.increment-version.outputs.version }}
          git push origin ${{ steps.increment-version.outputs.version }}
          
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with:
        java-version: 21
        distribution: temurin
        
    - name: Maven Clean Verify ## Maven version available on ubuntu-latest. If you need another version - install separately.
      run: mvn clean verify
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.REPO_NAME }}/mvn:${{ steps.increment-version.outputs.version }}
          ${{ secrets.REPO_NAME }}/mvn:latest
